# https://github.com/hexojs/hexo-starter/blob/master/_config.yml

# 6
title: 星
subtitle: 星的博客
description: 一些踩坑总结
keywords: 星 博客 star2000
author: 星
language: zh-CN
timezone: Asia/Shanghai

# 16
url: https://blog.star2000.work
pretty_urls:
  trailing_index: false

# 24
source_dir: 源
tag_dir: 标签
archive_dir: 归档
category_dir: 分类

# 43
post_asset_folder: true

# 62
default_category: 未分类

# 81
per_page: 0

# 87
theme: next

# 91
deploy:
  type: git
  name: 星
  email: i@star2000.work
  repo: https://xing2000:TENCENT_TOKEN@git.dev.tencent.com/xing2000/xing2000.coding.me

neat_enable: true
neat_html:
  exclude:
    - "**/*.md"
neat_css:
  exclude:
    - "**/*.min.css"
neat_js:
  exclude:
    - "**/*.min.js"
    - "**/js/algolia-search.js"
    - "**/js/next-boot.js"
    - "**/js/bookmark.js"
    - "**/js/local-search.js"
    - "**/js/utils.js"
    - "**/js/schemes/muse.js"
    - "**/js/schemes/pisces.js"

sitemap:
  template: ./sitemap_template.xml
