on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with:
          node-version: "*"

      - run: |
          git clone --depth=1 ${{ github.repositoryUrl }} .
          git clone --depth=1 https://github.com/theme-next/hexo-theme-next themes/next
          npm i --production
          sed -i "s|CODING_TOKEN|${{ secrets.CODING_TOKEN }}|" _config.yml
          sed -i "s|CODING_REPO|${{ secrets.CODING_REPO }}|" _config.yml
          npm run deploy
