on:
  push:
    paths-ignore:
      - .github/workflows/static.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: true
      - name: 恢复上次修改时间
        run: git ls-files -z | while read -d '' path; do touch -d "$(git log -1 --format="@%ct" "$path")" "$path"; done
      - uses: actions/setup-node@master
        with:
          node-version: "*"
      - name: 部署
        run: |
          sed -i "s|CODING_TOKEN|${{ secrets.CODING_TOKEN }}|" _config.yml
          npm i --production
          npm run deploy
