on:
  push:
    paths:
      - .github/workflows/ssr-download.yml
  schedule:
    - cron: "0 0 1 * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          wget github.com/xcxnig/ssr-download/raw/master/potatso-lite.ipa
          wget github.com/xcxnig/ssr-download/raw/master/potatso-lite.plist
          wget github.com/xcxnig/ssr-download/raw/master/ssr-mac.dmg
          wget github.com/xcxnig/ssr-download/raw/master/ssr-win.7z
          wget github.com/xcxnig/ssr-download/raw/master/ssrr-android.apk
          sed -i "s|raw.githubusercontent.com/xcxnig/ssr-download/master|ssr-download.star2000.work|" potatso-lite.plist
          git init
          git add .
          git config user.name ${{ github.event.pusher.name }}
          git config user.email ${{ github.event.pusher.email }}
          git commit -m '自动同步'
          git push -f https://star2000:${{ secrets.CODING_TOKEN }}@e.coding.net/${{ secrets.CODING_REPO }}/ssr-download master:master
