on:
  push:
    paths:
      - .github/workflows/static.yml
  schedule:
    - cron: "0 0 * * 0"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone --depth=1 https://${{ secrets.CODING_TOKEN }}@e.coding.net/xing2000/static .

          wget -qO aria2-64bit.zip $(wget -qO- api.github.com/repos/aria2/aria2/releases?per_page=1 | jq -r '.[0].assets[].browser_download_url | select(contains("win-64bit"))')
          unzip -p aria2-64bit.zip */aria2c.exe > aria2c-64bit.exe
          rm -f aria2-64bit.zip

          wget -qO aria2-32bit.zip $(wget -qO- api.github.com/repos/aria2/aria2/releases?per_page=1 | jq -r '.[0].assets[].browser_download_url | select(contains("win-32bit"))')
          unzip -p aria2-32bit.zip */aria2c.exe > aria2c-32bit.exe
          rm -f aria2-32bit.zip

          git add -A
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git commit -am '自动更新' --allow-empty
          git push
