on:
  push:
    paths:
      - .github/workflows/static.yml
  schedule:
    - cron: "0 0 * * 0"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          wget -qO 1.zip $(wget -qO- api.github.com/repos/2dust/v2rayN/releases?per_page=1 | jq -r '.[0].assets[0].browser_download_url')
          wget -qO 1.apk $(wget -qO- api.github.com/repos/2dust/v2rayNG/releases?per_page=1 | jq -r '.[0].assets[0].browser_download_url')
          wget -qO 1.dmg $(wget -qO- api.github.com/repos/yanue/V2rayU/releases?per_page=1 | jq -r '.[0].assets[0].browser_download_url')

          wget -qO aria2-64bit.zip $(wget -qO- api.github.com/repos/aria2/aria2/releases?per_page=1 | jq -r '.[0].assets[].browser_download_url | select(contains("win-64bit"))')
          unzip -p aria2-64bit.zip */aria2c.exe > aria2c-64bit.exe
          rm -f aria2-64bit.zip

          wget -qO aria2-32bit.zip $(wget -qO- api.github.com/repos/aria2/aria2/releases?per_page=1 | jq -r '.[0].assets[].browser_download_url | select(contains("win-32bit"))')
          unzip -p aria2-32bit.zip */aria2c.exe > aria2c-32bit.exe
          rm -f aria2-32bit.zip

          git init
          git add .
          git config user.name star2000
          git config user.email i@star2000.work
          git commit -m '自动同步'
          git push -f https://${{ secrets.CODING_TOKEN }}@e.coding.net/xing2000/static master:master
